### ISSUE TITLE
Déterminer un comportement lorsque les annotations ne conviennent pas un type d'étude

### ISSUE THREAD

**Issue by CedricJean** [Ownmarc/universal-data-tool#11]
Example avoir des annotations de Image Classification, mais avoir comme type d'étude Image segmentation

**Comment by Ownmarc** [comment]
Est-ce que tu veux dire lorsque le projet UDT en cours est autre que celui qu'on load avec le fichier à partir d'AWS ?

**Comment by CedricJean** [comment]
Exactement

**Comment by Ownmarc** [comment]
j'ai vu un issue dans le projet UDT à ce propos, laisse moi le retrouver

**Comment by Ownmarc** [comment]
https://github.com/UniversalDataTool/universal-data-tool/issues/82

**Comment by CedricJean** [comment]
Ok donc il faut laisser le choix à l'utilisateur, c'est bon à savoir

**Comment by Ownmarc** [comment]
Tu fermeras l'issue lorsque tu considereras que ce sera bon.

**Comment by CedricJean** [comment]
Je vais faire quelque modif pour cela après je fermerai
