### ISSUE TITLE
À discuter : Gérer un folder Data avec un mix de fichier (vidéo, image, bande de son ...)

### ISSUE THREAD

**Issue by CedricJean** [Ownmarc/universal-data-tool#12]
Ceci est à faire seulement si rien d'autre à faire.

Le comportement actuel est indéterminé.

**Comment by Ownmarc** [comment]
Pose la question sur le reppo UDT et link le issue ici stp.

**Comment by CedricJean** [comment]
Je l'ai fait sur le canal slack vu que ce n'est pas vraiment une tâche.
