### ISSUE TITLE
Lors d'un chargement S3 mettre à jour le nom du fichier

### ISSUE THREAD

**Issue by CedricJean** [Ownmarc/universal-data-tool#21]

**Comment by Ownmarc** [comment]
En fait je pense que c'est de setter le nom lorsqu'on import un projet à partir de S3 si le fichier d'annotations existe. Ca va nous permettre d'updater le bon projet ensuite lors du save.

**Comment by CedricJean** [comment]
Effectivement à condition que le nom du fichier ne soit pas changer entre temps

**Comment by Ownmarc** [comment]
Normalement il ne faudrait pas toucher le nom du projet effectivement suite à sa création. On pourra revisiter cela le jour ou on créera différentes versions d'annotations

**Comment by CedricJean** [comment]
Ok tu es sûr il faudrait le rendre intouchable je pense qu'on devrait plutôt que de créer un nouveau file lors de la sauvegarde plutôt renommer le file existant

**Comment by Ownmarc** [comment]
C'est peut-être un peu hors du scope de notre feature.. laissons comme ca pour le moment et si jamais ca cause problème on avisera
