### ISSUE TITLE
Créer une reconnaissance des extensions plus exhaustive pour les if conditionnels

### ISSUE THREAD

**Issue by CedricJean** [Ownmarc/universal-data-tool#3]
Les if conditionnels qui vise à reconnaître si un fichier est une vidéo ou une image ne couvrent pas toutes les possibilités.

**Comment by Ownmarc** [comment]
Yes, ca prend ca avant notre premier PR pour images

**Comment by CedricJean** [comment]
Actuellement, c'est fonctionnel pour le besoin actuel et je pense qu'on devra ajouter les extensions manquantes au fur-à-mesure

**Comment by CedricJean** [comment]
c'est pour ça que je ne ferme pas l'issue
