### ISSUE TITLE
Lors de la creation d'un nouv util AWS il reste bloqué sur Complete your Sign Up

### ISSUE THREAD

**Issue by CedricJean** [Ownmarc/universal-data-tool#44]

**Comment by Ownmarc** [comment]
humm, pas normal, on s'en parle demain matin, je pense que ca va te prendre un accès à Cognito pour corriger ca

**Comment by CedricJean** [comment]
Ok pas de prob

**Comment by CedricJean** [comment]
J'ai essayé sur ma nouvelle branche et ça semble corrigé par magie

**Comment by Ownmarc** [comment]
Je pense que ca me l'avait fait un fois, je crois que c'est quand les config d'authentification sont mal set-up que ca fait ca

**Comment by CedricJean** [comment]
Ok je la ferme dans ce cas
